/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChapterId = IDL.Text;
export const SubjectId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Bookmark = IDL.Record({
  'chapterId' : ChapterId,
  'addedAt' : Timestamp,
  'subjectId' : SubjectId,
});
export const Chapter = IDL.Record({
  'id' : ChapterId,
  'title' : IDL.Text,
  'subjectId' : SubjectId,
  'number' : IDL.Nat,
});
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Timestamp,
});
export const ProgressSummary = IDL.Record({
  'avgScore' : IDL.Nat,
  'totalCompleted' : IDL.Nat,
  'totalBookmarks' : IDL.Nat,
  'totalQuizzesTaken' : IDL.Nat,
});
export const QuizScore = IDL.Record({
  'subject' : SubjectId,
  'chapterId' : ChapterId,
  'score' : IDL.Nat,
  'takenAt' : Timestamp,
  'totalQuestions' : IDL.Nat,
});
export const Subject = IDL.Record({
  'id' : SubjectId,
  'name' : IDL.Text,
  'emoji' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBookmark' : IDL.Func([ChapterId, SubjectId], [], []),
  'askAssistant' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearChatHistory' : IDL.Func([], [], []),
  'clearMyOpenAIApiKey' : IDL.Func([], [], []),
  'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapters' : IDL.Func([SubjectId], [IDL.Vec(Chapter)], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getProgressSummary' : IDL.Func([], [ProgressSummary], ['query']),
  'getRecentQuizScores' : IDL.Func([IDL.Nat], [IDL.Vec(QuizScore)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMyOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markChapterComplete' : IDL.Func([ChapterId, SubjectId], [], []),
  'removeBookmark' : IDL.Func([ChapterId], [], []),
  'saveQuizScore' : IDL.Func([SubjectId, ChapterId, IDL.Nat, IDL.Nat], [], []),
  'setMyOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChapterId = IDL.Text;
  const SubjectId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Bookmark = IDL.Record({
    'chapterId' : ChapterId,
    'addedAt' : Timestamp,
    'subjectId' : SubjectId,
  });
  const Chapter = IDL.Record({
    'id' : ChapterId,
    'title' : IDL.Text,
    'subjectId' : SubjectId,
    'number' : IDL.Nat,
  });
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Timestamp,
  });
  const ProgressSummary = IDL.Record({
    'avgScore' : IDL.Nat,
    'totalCompleted' : IDL.Nat,
    'totalBookmarks' : IDL.Nat,
    'totalQuizzesTaken' : IDL.Nat,
  });
  const QuizScore = IDL.Record({
    'subject' : SubjectId,
    'chapterId' : ChapterId,
    'score' : IDL.Nat,
    'takenAt' : Timestamp,
    'totalQuestions' : IDL.Nat,
  });
  const Subject = IDL.Record({
    'id' : SubjectId,
    'name' : IDL.Text,
    'emoji' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBookmark' : IDL.Func([ChapterId, SubjectId], [], []),
    'askAssistant' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearChatHistory' : IDL.Func([], [], []),
    'clearMyOpenAIApiKey' : IDL.Func([], [], []),
    'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapters' : IDL.Func([SubjectId], [IDL.Vec(Chapter)], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getProgressSummary' : IDL.Func([], [ProgressSummary], ['query']),
    'getRecentQuizScores' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QuizScore)],
        ['query'],
      ),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMyOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markChapterComplete' : IDL.Func([ChapterId, SubjectId], [], []),
    'removeBookmark' : IDL.Func([ChapterId], [], []),
    'saveQuizScore' : IDL.Func(
        [SubjectId, ChapterId, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'setMyOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };