/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bookmark {
  'chapterId' : ChapterId,
  'addedAt' : Timestamp,
  'subjectId' : SubjectId,
}
export interface Chapter {
  'id' : ChapterId,
  'title' : string,
  'subjectId' : SubjectId,
  'number' : bigint,
}
export type ChapterId = string;
export interface ChatMessage {
  'content' : string,
  'role' : MessageRole,
  'timestamp' : Timestamp,
}
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export interface ProgressSummary {
  'avgScore' : bigint,
  'totalCompleted' : bigint,
  'totalBookmarks' : bigint,
  'totalQuizzesTaken' : bigint,
}
export interface QuizScore {
  'subject' : SubjectId,
  'chapterId' : ChapterId,
  'score' : bigint,
  'takenAt' : Timestamp,
  'totalQuestions' : bigint,
}
export interface Subject { 'id' : SubjectId, 'name' : string, 'emoji' : string }
export type SubjectId = string;
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBookmark' : ActorMethod<[ChapterId, SubjectId], undefined>,
  'askAssistant' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearChatHistory' : ActorMethod<[], undefined>,
  'clearMyOpenAIApiKey' : ActorMethod<[], undefined>,
  'getBookmarks' : ActorMethod<[], Array<Bookmark>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapters' : ActorMethod<[SubjectId], Array<Chapter>>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getProgressSummary' : ActorMethod<[], ProgressSummary>,
  'getRecentQuizScores' : ActorMethod<[bigint], Array<QuizScore>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMyOpenAIConfigured' : ActorMethod<[], boolean>,
  'markChapterComplete' : ActorMethod<[ChapterId, SubjectId], undefined>,
  'removeBookmark' : ActorMethod<[ChapterId], undefined>,
  'saveQuizScore' : ActorMethod<
    [SubjectId, ChapterId, bigint, bigint],
    undefined
  >,
  'setMyOpenAIApiKey' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];